name: swipe
description: An experiment in swiping functions
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  e2e: ^0.6.1
  firebase_analytics:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core
  flutter_app_badger: ^1.1.2
  flutter:
    sdk: flutter

  # stream_chat_flutter: ^latest_version
  # stream_chat_persistence: ^latest_version
  flutter_local_notifications: ^2.0.2
  flutter_svg: ^0.19.3
  flutter_secure_storage: ^3.3.5
  yaml: ^2.2.1
  uuid: ^2.2.2
  streaming_shared_preferences: ^1.0.2
  lottie: ^0.7.0+1
  
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5

  flutter_login: ^1.0.14
  clipboard: ^0.1.2+8
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+11
  cloudinary_client: ^0.0.9
  toast: ^0.1.5
  google_maps_flutter: ^1.0.6
  flutter_polyline_points: ^0.1.0
  geolocator: ^5.1.4+2
  share: any

dependency_overrides:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../../firebase_core/firebase_core_web

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  flutter_launcher_icons: ^0.8.1
  test: any

flutter:
  assets:
    - assets/
    - pubspec.lock
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
