name: swipe
description: An experiment in swiping functions
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_app_badger: ^1.2.0
  flutter:
    sdk: flutter

    # swipe shell
  permission_handler: ^8.0.1
  path_provider: ^2.0.2
  flutter_login: ^2.0.0-nullsafety.0
  clipboard: ^0.1.3
  simple_animations: ^3.0.0-nullsafety.0
  # toast: ^0.1.5
  share: ^2.0.4
  # cloudinary_client: ^0.0.9
  # google_maps_flutter: ^2.0.6
  geolocator: ^7.0.3

    # firebase
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1
  firebase_analytics: ^8.1.1
  cloud_firestore: ^2.2.1

    # chat
  stream_chat_flutter: ^2.0.0-nullsafety.4
  stream_chat_persistence: ^2.0.0-nullsafety.2
  flutter_local_notifications: ^6.0.0
  streaming_shared_preferences: ^2.0.0
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.22.0
  yaml: ^3.1.0
  uuid: ^3.0.4
  lottie: ^1.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  flutter_launcher_icons: ^0.9.0
  test: ^1.16.8

flutter:
  assets:
    - assets/
    - assets/demo/dorothy/1.jpeg
    - assets/demo/donghee/1.jpg
    - assets/demo/donghee/2.jpg
    - assets/demo/donghee/3.jpg
    - assets/demo/jackblack/1.png
    - assets/demo/jackblack/2.jpg
    - assets/demo/jackblack/3.jpg
    - assets/demo/jackblack/4.jpg
    - assets/demo/iu/1.jpg
    - assets/demo/iu/2.jpg
    - assets/demo/iu/3.jpg
    - assets/demo/iu/4.jpg
    - assets/demo/iu/5.jpg
    - assets/demo/jennie/1.jpg
    - assets/demo/jennie/2.jpg
    - assets/demo/jennie/3.png
    - assets/demo/jennie/4.jpg
    - assets/demo/paige/1.jpg
    - assets/demo/snoop/1.png
    - assets/demo/snoop/2.jpg
    - assets/demo/snoop/3.jpg
    - assets/demo/tigerwoods/1.jpg
    - assets/demo/tigerwoods/2.jpg
    - assets/demo/tigerwoods/3.jpg
    - pubspec.lock
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
