name: swipe
description: An experiment in swiping functions
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_app_badger: ^1.1.2
  flutter:
    sdk: flutter
  stream_chat_flutter: ^latest_version
  stream_chat_persistence: ^latest_version
  flutter_local_notifications: ^2.0.2
  flutter_svg: ^0.19.3
  flutter_secure_storage: ^3.3.5
  yaml: ^2.2.1
  uuid: ^2.2.2
  streaming_shared_preferences: ^1.0.2
  lottie: ^0.7.0+1

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  test: ^1.16.0

flutter:
  assets:
    - assets/
    - pubspec.lock
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
